import { validateEnv } from '$lib/env';

const STOREFRONT_URL = import.meta.env.VITE_STOREFRONT_URL;
validateEnv(STOREFRONT_URL, 'VITE_STOREFRONT_URL');

const SHOPIFY_STORE_NAME = import.meta.env.VITE_SHOPIFY_STORE_NAME;
validateEnv(SHOPIFY_STORE_NAME, 'VITE_SHOPIFY_STORE_NAME');

const STOREFRONT_API_TOKEN = import.meta.env.VITE_SHOPIFY_STOREFRONT_API_TOKEN;
validateEnv(STOREFRONT_API_TOKEN, 'VITE_SHOPIFY_STOREFRONT_API_TOKEN');

export { STOREFRONT_URL, SHOPIFY_STORE_NAME, STOREFRONT_API_TOKEN };
